package queue

import "fmt"

// ComposePRBody renders the PR description. Exported for test visibility.
func ComposePRBody(taskID int64, branch, summary string, tokens int64, costCents int) string {
	return fmt.Sprintf(
		"Task #%d\nBranch: %s\nTokens: %d  Cost: $%.2f\n\n---\n%s\n\n---\nGenerated by era. Do not merge without reading the diff.",
		taskID, branch, tokens, float64(costCents)/100.0, Truncate(summary, 2500),
	)
}

// Truncate caps s at `budget` bytes, backing up to a rune boundary.
func Truncate(s string, budget int) string {
	if len(s) <= budget {
		return s
	}
	cut := budget
	for cut > 0 && (s[cut]&0xC0) == 0x80 {
		cut--
	}
	return s[:cut]
}
