package queue_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/vaibhav0806/era/internal/queue"
)

func TestComposePRBody_IncludesEssentialFields(t *testing.T) {
	body := queue.ComposePRBody(42, "agent/42/foo", "Pi's answer prose", 1500, 123)
	require.Contains(t, body, "Task #42")
	require.Contains(t, body, "Branch: agent/42/foo")
	require.Contains(t, body, "Tokens: 1500")
	require.Contains(t, body, "Cost: $1.23")
	require.Contains(t, body, "Pi's answer prose")
	require.Contains(t, body, "Generated by era")
}

func TestComposePRBody_TruncatesLongSummary(t *testing.T) {
	longText := strings.Repeat("x", 5000)
	body := queue.ComposePRBody(1, "b", longText, 0, 0)
	require.Less(t, len(body), 3500, "body should cap to <3500 chars even for huge summaries")
}

func TestTruncate_BacksUpToRuneBoundary(t *testing.T) {
	s := strings.Repeat("€", 10) // 30 bytes
	got := queue.Truncate(s, 15)
	require.True(t, len(got) <= 15)
	require.True(t, strings.HasPrefix(s, got))
}
