// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Approval struct {
	ID          int64        `json:"id"`
	TaskID      int64        `json:"task_id"`
	Reason      string       `json:"reason"`
	Status      string       `json:"status"`
	RequestedAt time.Time    `json:"requested_at"`
	ResolvedAt  sql.NullTime `json:"resolved_at"`
}

type Event struct {
	ID        int64     `json:"id"`
	TaskID    int64     `json:"task_id"`
	Kind      string    `json:"kind"`
	Payload   string    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

type Task struct {
	ID            int64          `json:"id"`
	Description   string         `json:"description"`
	Status        string         `json:"status"`
	BranchName    sql.NullString `json:"branch_name"`
	Summary       sql.NullString `json:"summary"`
	Error         sql.NullString `json:"error"`
	TokensUsed    int64          `json:"tokens_used"`
	CostCents     int64          `json:"cost_cents"`
	CreatedAt     time.Time      `json:"created_at"`
	StartedAt     sql.NullTime   `json:"started_at"`
	FinishedAt    sql.NullTime   `json:"finished_at"`
	TargetRepo    string         `json:"target_repo"`
	PrNumber      sql.NullInt64  `json:"pr_number"`
	BudgetProfile string         `json:"budget_profile"`
}
