// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AppendEvent(ctx context.Context, arg AppendEventParams) error
	ClaimNextQueuedTask(ctx context.Context) (Task, error)
	// queries/tasks.sql
	CreateTask(ctx context.Context, description string) (Task, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	ListEventsForTask(ctx context.Context, taskID int64) ([]Event, error)
	ListRecentTasks(ctx context.Context, limit int64) ([]Task, error)
	ListTasksBetween(ctx context.Context, arg ListTasksBetweenParams) ([]Task, error)
	MarkTaskCompleted(ctx context.Context, arg MarkTaskCompletedParams) error
	MarkTaskFailed(ctx context.Context, arg MarkTaskFailedParams) error
	SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) error
}

var _ Querier = (*Queries)(nil)
