// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AppendEvent(ctx context.Context, arg AppendEventParams) error
	ClaimNextQueuedTask(ctx context.Context) (Task, error)
	// queries/tasks.sql
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	ListEventsForTask(ctx context.Context, taskID int64) ([]Event, error)
	ListRecentTasks(ctx context.Context, limit int64) ([]Task, error)
	ListRunningTaskIDs(ctx context.Context) ([]int64, error)
	ListTasksBetween(ctx context.Context, arg ListTasksBetweenParams) ([]Task, error)
	MarkRunningTasksFailed(ctx context.Context, error sql.NullString) (int64, error)
	MarkTaskCompleted(ctx context.Context, arg MarkTaskCompletedParams) error
	MarkTaskFailed(ctx context.Context, arg MarkTaskFailedParams) error
	SetBudgetProfile(ctx context.Context, arg SetBudgetProfileParams) error
	SetPRNumber(ctx context.Context, arg SetPRNumberParams) error
	SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) error
}

var _ Querier = (*Queries)(nil)
