// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (task_id, kind, payload) VALUES (?, ?, ?)
`

type AppendEventParams struct {
	TaskID  int64  `json:"task_id"`
	Kind    string `json:"kind"`
	Payload string `json:"payload"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent, arg.TaskID, arg.Kind, arg.Payload)
	return err
}

const claimNextQueuedTask = `-- name: ClaimNextQueuedTask :one
UPDATE tasks SET status = 'running', started_at = CURRENT_TIMESTAMP
WHERE id = (SELECT id FROM tasks WHERE status = 'queued' ORDER BY id ASC LIMIT 1)
RETURNING id, description, status, branch_name, summary, error, created_at, started_at, finished_at, tokens_used, cost_cents
`

func (q *Queries) ClaimNextQueuedTask(ctx context.Context) (Task, error) {
	row := q.db.QueryRowContext(ctx, claimNextQueuedTask)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Status,
		&i.BranchName,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TokensUsed,
		&i.CostCents,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (description, status)
VALUES (?, 'queued')
RETURNING id, description, status, branch_name, summary, error, created_at, started_at, finished_at, tokens_used, cost_cents
`

// queries/tasks.sql
func (q *Queries) CreateTask(ctx context.Context, description string) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Status,
		&i.BranchName,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TokensUsed,
		&i.CostCents,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, description, status, branch_name, summary, error, created_at, started_at, finished_at, tokens_used, cost_cents FROM tasks WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Status,
		&i.BranchName,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TokensUsed,
		&i.CostCents,
	)
	return i, err
}

const listEventsForTask = `-- name: ListEventsForTask :many
SELECT id, task_id, kind, payload, created_at FROM events WHERE task_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListEventsForTask(ctx context.Context, taskID int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTasks = `-- name: ListRecentTasks :many
SELECT id, description, status, branch_name, summary, error, created_at, started_at, finished_at, tokens_used, cost_cents FROM tasks ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListRecentTasks(ctx context.Context, limit int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listRecentTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Status,
			&i.BranchName,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TokensUsed,
			&i.CostCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskCompleted = `-- name: MarkTaskCompleted :exec
UPDATE tasks SET
    status       = 'completed',
    branch_name  = ?,
    summary      = ?,
    tokens_used  = ?,
    cost_cents   = ?,
    finished_at  = CURRENT_TIMESTAMP
WHERE id = ?
`

type MarkTaskCompletedParams struct {
	BranchName sql.NullString `json:"branch_name"`
	Summary    sql.NullString `json:"summary"`
	TokensUsed int64          `json:"tokens_used"`
	CostCents  int64          `json:"cost_cents"`
	ID         int64          `json:"id"`
}

func (q *Queries) MarkTaskCompleted(ctx context.Context, arg MarkTaskCompletedParams) error {
	_, err := q.db.ExecContext(ctx, markTaskCompleted,
		arg.BranchName,
		arg.Summary,
		arg.TokensUsed,
		arg.CostCents,
		arg.ID,
	)
	return err
}

const markTaskFailed = `-- name: MarkTaskFailed :exec
UPDATE tasks SET status = 'failed', error = ?, finished_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type MarkTaskFailedParams struct {
	Error sql.NullString `json:"error"`
	ID    int64          `json:"id"`
}

func (q *Queries) MarkTaskFailed(ctx context.Context, arg MarkTaskFailedParams) error {
	_, err := q.db.ExecContext(ctx, markTaskFailed, arg.Error, arg.ID)
	return err
}
